### PR TITLE
[Add] Added conanfile

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Added a conanfile so we can use this in tenacity

### CODE REVIEW

**Comment by Be-ing** [comment]
I'm confused why a file for packaging belongs in the repository for the library.

**Comment by Be-ing** [comment]
Shouldn't this go to https://github.com/tenacityteam/conan-recipes ?

**Comment by AnotherFoxGuy** [comment]
It doesn't need to be in a separate repo: https://docs.conan.io/en/latest/creating_packages/package_repo.html
I personally find it easier to have in the same repo so you can update the Conan pkg when you release a new version

**Comment by AnotherFoxGuy** [comment]
But if you prefer it in the https://github.com/tenacityteam/conan-recipes repo I will move it there

**Comment by Be-ing** [comment]
Yes please do that instead. Also use the new 236 tag.

**Pull request closed without merging**
