### PR TITLE
Fix const strings declared as char*

### PR DESCRIPTION
**Pull request by Veratil**
Fixes the build warnings seen during build. You can see them in the logs here: https://github.com/tenacityteam/portsmf/runs/3090554258?check_suite_focus=true#step:4:1

Ran the tests (except 17, 19, and 21 as those still segfault; 32 and 33 aren't running since a file is missing it looks like) and all look to be working still.

### CODE REVIEW

**Comment by Be-ing** [comment]
> Ran the tests (except 17, 19, and 21 as those still segfault; 32 and 33 aren't running since a file is missing it looks like) and all look to be working still.

If you want to refactor these into a proper testing framework so we can run them on CI, that would be awesome :)

**Comment by Be-ing** [comment]
```
 /home/runner/work/portsmf/portsmf/src/allegro.cpp: In member function ‘virtual Alg_event*& Alg_seq::operator[](int)’:
/home/runner/work/portsmf/portsmf/src/allegro.cpp:2883:1: warning: control reaches end of non-void function [-Wreturn-type]
 2883 | }
      | ^
```
That's concerning, but that can be fixed in another PR.

**Comment by Be-ing** [comment]
const'ing more things is good, thanks.

**Comment by Veratil** [comment]
> 
> 
> > Ran the tests (except 17, 19, and 21 as those still segfault; 32 and 33 aren't running since a file is missing it looks like) and all look to be working still.
> 
> If you want to refactor these into a proper testing framework so we can run them on CI, that would be awesome :)

I was looking into that earlier. Currently working on cleaning up the files more (using C++ headers, removing unused ones, etc.).



> 
> 
> ```
>  /home/runner/work/portsmf/portsmf/src/allegro.cpp: In member function ‘virtual Alg_event*& Alg_seq::operator[](int)’:
> /home/runner/work/portsmf/portsmf/src/allegro.cpp:2883:1: warning: control reaches end of non-void function [-Wreturn-type]
>  2883 | }
>       | ^
> ```
> 
> That's concerning, but that can be fixed in another PR.

I'm not getting that error. I'll see if I can get it to show up though, otherwise not sure what to try.

**Comment by Be-ing** [comment]
Catch2 is a tiny C++ testing framework that seems to work well and integrates with CTest.

**Comment by Be-ing** [comment]
Clang and MSVC have more warnings. Take a look at the CI logs for those.

**Comment by Veratil** [comment]
> 
> 
> Clang and MSVC have more warnings. Take a look at the CI logs for those.

I'll hit these next, too! I'm using gcc 10.3.1, so maybe the 9.3.0 used in the Ubuntu build has a bug that's fixed later. I enabled all the warnings I could and never got it.



> 
> 
> Catch2 is a tiny C++ testing framework that seems to work well and integrates with CTest.

I saw some good recommendations for Catch, will take a look at it after some more cleanup.

**Pull request merged**
